### ISSUE TITLE
Vein mining does not function

### ISSUE THREAD

**Issue by TheOnlyJoeEnderman** [QuoteNat/vein_miner#10]
Even if it's the only mod installed. Could it be an api change in 5.6.1?

**Comment by Awkanimus** [comment]
For me, if I do not have "All blocks" setting enabled, I cannot get a vein of coal to vein mine. With the all blocks setting enabled, I can. @TheOnlyJoeEnderman have you attempted this with the "All Blocks" setting enabled? Also, if a tool doesn't have enough durability, it doesn't mine and until I figured that out, it felt like it wasn't working.

Edit: Added bit about durability.

**Comment by TheOnlyJoeEnderman** [comment]
How do I change the mod settings?

**Comment by Awkanimus** [comment]
To change the settings for singleplayer:
1. Launch minetest but don't enter a game
2. In the main menu, select  the "settings" tab
3. At the bottom left, click "All Settings"
4. In the search for all settings, type "vein"
5. Double click to enable / disable the flags
6. Click the singleplayer tab (there's no save button, it's instant)
7. Launch your game

The setting is more if a work around though .. I agree there is a bug.

**Comment by Awkanimus** [comment]
Note: I've explored this more thoroughly and submitted a pull request #12 which fixes this. 

Work around without the bug: change each setting once, start up a dummy world, then change them to whatever you want and it'll work. The problem is before they're changed, the values are not populated in minetest.conf and are being read as false despite the default values in settingtypes.txt.
